# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/edt_zcu102/edt_zcu102.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu102 || ORIG_REF_NAME==edt_zcu102} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_zynq_ultra_ps_e_0_1/edt_zcu102_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_1} -quiet] -quiet

# XDC: c:/Users/Adam/demo2/demo2.gen/sources_1/bd/edt_zcu102/edt_zcu102_ooc.xdc
